### ISSUE TITLE
Filter for publication date cannot be added.

### ISSUE THREAD

**Issue by b0wter** [b0wter/Podfilter#13]
There was a problem (System.InvalidOperationException: The entity type 'DateTimeParameter' was not found. Ensure that the entity type has been added to the model.
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
 at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState, Boolean forceStateWhenUnknownKey)
 at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
 at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
 at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
 at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
 at PodfilterRepository.Sqlite.SqliteSavedPodcastsRepository.Persist(SavedPodcast toPersist) in C:\Users\evil-\Documents\Podfilter\PodfilterRepository\Sqlite\SqliteRepository.cs:line 102
 at PodfilterWeb.Controllers.HomeController.CreateAndAddDbPodfilterUrl(String podcastUrl) in C:\Users\evil-\Documents\Podfilter\PodfilterWeb\Controllers\HomeController.cs:line 264). Please try again. If the problem persists contat the administrator.

**Comment by b0wter** [comment]
Added missing entry in the PfContext.
